app = 'talk-trace-ai'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-4x'
  memory = '2gb'
  cpus = 4
  memory_mb = 2048
